app/urls.py
# -*- encoding: utf-8 -*-


from django.urls import path, re_path
from .views import *
from django.views.generic.base import RedirectView

urlpatterns = [

    # The home page
    path('', SimulationsView.as_view(), name='home'),

    path('simulations', SimulationsView.as_view(), name='simulations'),
    path('simulations/new', NewSimulationView.as_view(), name='new-simulation'),
    path('simulations/<int:simulation_id>/',
         SimulationView.as_view(), name='simulation'),
    path('simulations/<int:simulation_id>/delete',
         delete_simulation, name='delete-simulation'),
    path('simulations/<int:simulation_id>/outputs/<int:output_id>/',
         OutputView.as_view(), name='output'),
    path('simulations/<int:simulation_id>/outputs/<int:output_id>/files/<path:output_file>',
         OutputFileView.as_view(), name='output-file'),
    path('simulations/<int:simulation_id>/outputs/<int:output_id>/log',
         OutputLogView.as_view(), name='output-log'),
    path('models', ModelsView.as_view(), name='models'),
    path('models/<int:model_id>/', ModelView.as_view(), name='model'),

]

core/urls.py
# -*- encoding: utf-8 -*-


from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route

    path('', include('authentication.urls')),  # Auth routes - login / register
    path('', include('app.urls'))             # UI Kits Html files
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
# -*- encoding: utf-8 -*-


from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext as _


class Model(models.Model):
    name = models.CharField('Name', max_length=200)
    description = models.TextField('Description', null=True, blank=True)
    image = models.CharField('Image', max_length=200)
    schema = models.JSONField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _('model')
        verbose_name_plural = _('models')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('model', kwargs={'model_id': self.pk})


STATE_PENDING = 0
STATE_RUNNING = 1
STATE_PASSED = 2
STATE_FALIED = 3
STATE_CHOICES = (
    (STATE_PENDING, 'Pending'),
    (STATE_RUNNING, 'Running'),
    (STATE_PASSED, 'Passed'),
    (STATE_FALIED, 'Falied')
)


class Simulation(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='simulations')
    model = models.ForeignKey(
        Model, on_delete=models.CASCADE, related_name='simulations')
    container = models.CharField('Container', max_length=256)
    parameters = models.FileField(upload_to='inputs/')
    state = models.IntegerField(choices=STATE_CHOICES, default=STATE_PENDING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Simulation')
        verbose_name_plural = _('Simulations')

    def __str__(self):
        return u'{0}'.format(self.id)

    def get_absolute_url(self):
        return reverse('simulation', kwargs={'simulation_id': self.pk})


class Output(models.Model):
    simulation = models.ForeignKey(
        Simulation, on_delete=models.CASCADE, related_name='outputs')
    result = models.FileField(upload_to='results/')
    log = models.FileField(upload_to='logs/')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Output')
        verbose_name_plural = _('Outputs')

    def __str__(self):
        return u'{0}'.format(self.id)

    def get_absolute_url(self):
        return reverse('output', kwargs={'output_id': self.pk})

authentication/models.py
# -*- encoding: utf-8 -*-


from django.db import models

# Create your models here.

core/templates/model.html
{% extends "layouts/base.html" %}

{% load markdown %}

{% block title %} Model - {{ model.name }}{% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
{% endblock stylesheets %}

{% block content %}

<div class="row">
    <div class="col-12 col-md-4">
        <div class="card">
            <div class="card-header  card-header-success">
                <h4 class="card-title">Model</h4>
                {% comment %} <p class="card-category"> - Last update: {{ model.updated_at | date }}</p> {% endcomment %}
            </div>
            <div class="card-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <div><b>ID: </b> {{ model.pk }}</div>
                        </div>

                        <div class="col-12 col-md-4">
                            <div><b>Name: </b> {{ model.name }}</div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div><b>Image: </b> {{ model.image }}</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div><b>Last update: </b> {{ model.updated_at | date }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-8">
        <div class="card">
            <div class="card-header card-header-info">
                <h4 class="card-title">Description</h4>
                {% comment %}
                <p class="card-category">Here is a subtitle for this table</p>
                {% endcomment %}
            </div>
            <div class="card-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="col">
                        {{ model.description | markdown }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}

core/templates/models.html
{% extends "layouts/base.html" %} {% block title %} Models {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Models</h4>
                {% comment %}
                <p class="card-category">Here is a subtitle for this table</p>
                {% endcomment %}
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="text-primary">
                            <th class="text-center">ID</th>
                            <th>Name</th>
                            <th>Image</th>
                            <th class="text-right">Actions</th>
                        </thead>
                        <tbody>
                            {% for model in models_list %}
                            <tr>
                                <td class="text-center"><a href="{{ model.get_absolute_url }}">{{ model.pk }}</a></td>
                                <td><a href="{{ model.get_absolute_url }}">{{ model.name }}</a></td>
                                <td>{{ model.image }}</td>
                                <td class="td-actions text-right">
                                    <a rel="tooltip" class="btn btn-info btn-simple"  href="{{ model.get_absolute_url }}">
                                        <i class="material-icons">visibility</i>
                                    </a>
                                </td>

                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/new-simulation.html
{% extends "layouts/base.html" %} {% block title %} New Simulation {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-text card-header-default">
                <div class="card-text">
                    <h4 class="card-title">New Simulations</h4>
                </div>
                {% comment %}
                <p class="card-category">Here is a subtitle for this table</p>
                {% endcomment %}
            </div>
            <div class="card-body">
                <form role="form" method="post" action="" enctype='multipart/form-data'>
                    {% csrf_token %}

                   <div class="container-fluid">


                        <div class="row my-4">
                            <div class="form-group col-12 col-lg-6">
                                <label for="id_model">{{ form.model.label }}</label>
                                {{ form.model }}
                            </div>
                        </div>

                        {{ form.parameters }}

                    </div>

                    {% comment %} <div class="form-group form-file-upload form-file-multiple">
                        <label for="id_files">Files</label>
                        {{ form.files }}
                    </div> {% endcomment %}

                    <div class="form-group">
                        <a href="{% url 'simulations' %}" class="btn btn-danger">Cancel</a>
                        <button type="submit" class="btn btn-success">Run</button>
                    </div>
                </form>
                <pre>{{ form.errors }}</pre>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{{ form.media }}
{% endblock javascripts %}

core/templates/output-file.html
{% extends "layouts/base.html" %}

{% load b64encode csv_to_html %}

{% block title %} Output - {{ name }}{% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
{% endblock stylesheets %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">
                    <a href="{% url 'output' output.simulation.pk output.pk %}">
                        <i class="material-icons">arrow_back</i>
                    </a>
                    Output - {{ name }}
                </h4>
                {% comment %}
                <p class="card-category">Here is a subtitle for this table</p>
                {% endcomment %}
            </div>
            <div class="card-body">
                <div class="container">
                    <div class="row">
                        <div class="col justify-content-center">
                            {% if type == 'image' %}
                                <img src="data:{{ mime }};base64,{{ file | b64encode }}" width="100%" height="auto">
                            {% elif type == 'video' %}
                                <video autoplay controls src="data:{{ mime }};base64,{{ file | b64encode}}" width="100%" height="auto">
                                    The "video" tag is not supported by your browser. Click [here] to download the video file.
                                </video>
                            {% elif type == 'audio' %}
                                <audio controls src="data:{{ mime }};base64,{{ file | b64encode}}" />
                            {% elif type == 'text' %}
                                {% if mime == 'text/csv' %}
                                    <div class="table-responsive">
                                        {{ file | csv_to_html }}
                                    <div>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}

core/templates/output-log.html
{% extends "layouts/base.html" %} {% block title %} Output Log - {{ output.pk }}{% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/themes/prism.min.css"
    integrity="sha512-tN7Ec6zAFaVSG3TpNAKtk4DOHNpSwKHxxrsiw4GHKESGPs5njn/0sMCUMl2svV4wo4BK/rCP7juYz+zx+l6oeQ=="
    crossorigin="anonymous"
/><link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/plugins/line-numbers/prism-line-numbers.min.css"
    integrity="sha512-cbQXwDFK7lj2Fqfkuxbo5iD1dSbLlJGXGpfTDqbggqjHJeyzx88I3rfwjS38WJag/ihH7lzuGlGHpDBymLirZQ=="
    crossorigin="anonymous"
/>
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/themes/prism-okaidia.min.css"
    integrity="sha512-mIs9kKbaw6JZFfSuo+MovjU+Ntggfoj8RwAmJbVXQ5mkAX5LlgETQEweFPI18humSPHymTb5iikEOKWF7I8ncQ=="
    crossorigin="anonymous"
/>
{% endblock stylesheets %} {% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">
                    <a href="{% url 'simulation' output.simulation.pk %}">
                        <i class="material-icons">arrow_back</i>
                    </a>
                    Output Log
                    <a
                        href="{{ output.log.url }}"
                        download rel="tooltip"
                        rel="tooltip"
                        class="btn btn-success btn-sm btn-just-icon"
                        data-placement="bottom"
                        title="Dowload"
                    >
                        <i class="material-icons">download</i>
                    </a>
                </h4>
                {% comment %}
                <p class="card-category">Here is a subtitle for this table</p>
                {% endcomment %}
            </div>
            <div class="card-body">
                <pre style="white-space: pre-wrap"><code class="line-numbers language-none" >{{ log_content }}</code></pre>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/components/prism-core.min.js"
    integrity="sha512-xR+IAyN+t9EBIOOJw5m83FTVMDsPd63IhJ3ElP4gmfUFnQlX9+eWGLp3P4t3gIjpo2Z1JzqtW/5cjgn+oru3yQ=="
    crossorigin="anonymous"
></script>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/plugins/autoloader/prism-autoloader.min.js"
    integrity="sha512-zc7WDnCM3aom2EziyDIRAtQg1mVXLdILE09Bo+aE1xk0AM2c2cVLfSW9NrxE5tKTX44WBY0Z2HClZ05ur9vB6A=="
    crossorigin="anonymous"
></script>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/plugins/line-numbers/prism-line-numbers.min.js"
    integrity="sha512-br8H6OngKoLht57WKRU5jz3Vr0vF+Tw4G6yhNN2F3dSDheq4JiaasROPJB1wy7PxPk7kV/+5AIbmoZLxxx7Zow=="
    crossorigin="anonymous"
></script>
{% endblock javascripts %}

core/templates/output.html
{% extends "layouts/base.html" %}

{% block title %} Output - {{ output.pk }}{% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
{% endblock stylesheets %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">
                    <a href="{% url 'simulation' output.simulation.pk %}">
                        <i class="material-icons">arrow_back</i>
                    </a>
                    Outputs
                    <a
                        href="{{ output.result.url }}"
                        download
                        rel="tooltip"
                        class="btn btn-success btn-sm btn-just-icon"
                        data-placement="bottom"
                        title="Dowload"
                    >
                        <i class="material-icons">download</i>
                    </a>
                </h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="text-primary">
                            <th>Type</th>
                            <th>Name</th>
                            <th class="text-right">Size</th>
                            <th class="text-right">Options</th>
                        </thead>
                        <tbody>
                        {% for file in files %}
                            <tr>
                                <td >
                                {% if file.isdir %}
                                    <span class="badge badge-secondary"> Directory</span>
                                {% elif file.isfile %}
                                    <span class="badge badge-success"> File</span>
                                {% endif %}
                                </td>
                                <td>{{ file.name }}</td>
                                <td class="text-right">{{ file.size | filesizeformat }}</td>
                                <td class="td-actions text-right">
                                    {% if file.isfile %}
                                    <a
                                        href="{% url 'output-file' output.simulation output.pk file.name %}"
                                        class="btn btn-info btn-sm btn-just-icon"
                                    >
                                        <i class="material-icons">visibility</i>
                                    </a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}

core/templates/page-403.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 403</h6>
                    <h4 class="card-title">
                        Access Denied
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/page-404.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 404</h6>
                    <h4 class="card-title">
                        Page not found
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/page-500.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 500</h6>
                    <h4 class="card-title">
                        Internal Server Error
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/simulation.html
{% extends "layouts/base.html" %}

{% block title %} Simulation - {{ simulation.pk }}{% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
{% endblock stylesheets %}

{% block content %}

<div class="row">
    <div class="col col-md-4">
        <div class="card">
            <div class="card-header card-header-text card-header-primary">
                <div class="card-text">
                    <h4 class="card-title">
                        <a href="{% url 'simulations' %}">
                            <i class="material-icons">arrow_back</i>
                        </a>
                        Simulation
                    </h4>
                </div>
            </div>
            <div class="card-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col"><b>ID:</b> {{ simulation.pk }}</div>
                        <div class="col">
                            {% if simulation.state == 0 %}
                            <span class="pull-right badge badge-warning">
                            {% elif simulation.state == 1 %}
                            <span class="pull-right badge badge-info">
                            {% elif simulation.state == 2 %}
                            <span class="pull-right badge badge-success">
                            {% elif simulation.state == 3 %}
                            <span class="pull-right badge badge-danger">
                            {%endif %}
                                {{ simulation.get_state_display }}
                            </span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <b>Model:</b>
                            <a href="{{ simulation.model.get_absolute_url }}">
                                {{ simulation.model }}
                            </a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <b>Parameters:</b>
                            {{ simulation.parameters }}
                            <a href="{{ simulation.parameters.url }}" rel="tooltip" class="btn btn-success btn-just-icon btn-sm" download>
                                <i class="material-icons">download</i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col col-md-8">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Outputs</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="text-primary">
                            <th class="text-center">ID</th>
                            <th>Output</th>
                            <th>Log</th>
                            <th>Created at</th>
                        </thead>
                        <tbody>
                            {% for output in simulation.outputs.all %}
                            <tr>
                                <td class="text-center">
                                    <a href="{% url 'output' simulation.pk output.pk %}">
                                        {{ output.pk }}
                                    </a>
                                </td>
                                <td class="td-actions" >
                                    {% if output.result %}
                                    <a href="{% url 'output' simulation.pk output.pk %}" class="btn btn-info btn-simple">Result </a>
                                    <a href="{{ output.result.url }}" rel="tooltip" class="btn btn-success btn-simple" download>
                                        <i class="material-icons">download</i>
                                    </a>
                                    {% else %}
                                    <button href="" class="btn btn-other btn-simple" disabled>Result </button>
                                    {% endif %}
                                </td>
                                <td class="td-actions">
                                    <a href="{% url 'output-log' simulation.pk output.pk %}" class="btn btn-info btn-simple">Logs</a>
                                    <a href="{{ output.log.url }}" rel="tooltip" class="btn btn-success btn-simple" download>
                                        <i class="material-icons">download</i>
                                    </a>
                                </td>
                                <td>{{ output.created_at }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}

core/templates/simulations.html
{% extends "layouts/base.html" %}

{% block title %} Simulations {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Simulations</h4>
                {% comment %}
                <p class="card-category">Here is a subtitle for this table</p>
                {% endcomment %}
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="text-primary">
                            <th class="text-center">ID</th>
                            <th>Model</th>
                            <th>State</th>
                            <th>Created at</th>
                            <th class="text-right">Actions</th>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="text-center">
                                    <a
                                        href="{% url 'new-simulation' %}"
                                        class="btn btn-outline-default btn-just-icon btn-sm"
                                        rel="tooltip"
                                        data-placement="right"
                                        title="New Simulation"
                                    >
                                        <i class="material-icons">add</i>
                                    </a>
                                </td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            {% for simulation in simulations_list %}
                            <tr>
                                <td class="text-center"><a href="{{ simulation.get_absolute_url }}">{{ simulation.pk }}</a></td>
                                <td><a href="{{ simulation.model.get_absolute_url }}">{{ simulation.model }}</a></td>
                                <td>
                                    {% if simulation.state == 0 %}
                                    <span class="badge badge-warning">
                                    {% elif simulation.state == 1 %}
                                    <span class="badge badge-info">
                                    {% elif simulation.state == 2 %}
                                    <span class="badge badge-success">
                                    {% elif simulation.state == 3 %}
                                    <span class="badge badge-danger">
                                    {%endif %}
                                        {{ simulation.get_state_display }}
                                    </span>
                                </td>
                                <td>{{ simulation.created_at }}</td>
                                <td class="td-actions text-right">
                                    <a rel="tooltip" class="btn btn-info btn-simple" href="{{ simulation.get_absolute_url }}">
                                        <i class="material-icons">visibility</i>
                                    </a>
                                    <a rel="tooltip" class="btn btn-danger btn-simple" href="{% url 'delete-simulation' simulation.pk %}">
                                        <i class="material-icons">delete</i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}

core/templates/test.html
{% extends "layouts/base.html" %}

{% block title %} Page Blank {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Page Blank</h6>
                    <h4 class="card-title">
                        Add your content
                    </h4>
                    <form action="">
                        {{ form.inputs }}
                        {{ form.media }}
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}